name: unit-test

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:

  golang-test:
    name: Golang-unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
        id: go

      - name: Test
        run: |
          GO111MODULE=auto go test ./... -coverprofile coverage.out
          COVERAGE=`go tool cover -func=coverage.out | grep total: | grep -Eo '[0-9]+\.[0-9]+'`
          echo $COVERAGE
          COLOR=orange
          if (( $(echo "$COVERAGE <= 50" | bc -l) )) ; then
          COLOR=red
          elif (( $(echo "$COVERAGE > 80" | bc -l) )); then
          COLOR=green
          fi
          curl "https://img.shields.io/badge/coverage-$COVERAGE%25-$COLOR" > badge.svg
